/*
 * This source file was generated by the Gradle 'init' task
 */
package quiz4a;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


class AppTest {
    

    //ตัวอย่าง 1 ให้สร้าง Employee Employee(1, "John Doe", 50000) และตรวจสอบว่าเงินเดือน เป็น 50000
    @Test void createEmployee(int employeeId, String name, double salary) {
      Employee emp = new Employee (1, "John Doe", 50000);
            assertEquals(emp,salary,"Salary = 50000");
      
    }

    //ข้อ 2 ตรวจสอบว่า Salary ตั้งให้ติดลบไม่ได้
    @Test void SalaryCannotBeNegative(int employeeId, String name, double salary) {
        Employee emp = new Employee (1, "John Doe", 50000);
        assertThrows(IllegalArgumentException.class, () -> new SalaryCannotBeNegative1 (-50000));
    }

    //ข้อ 3 ตรวจสอบว่า Bonus เป็น 20% ของ เงินเดือน(Salary)
    //ต้องมีการแก้ไข code ใน Manager.java ให้ถูกต้อง
    @Test void Bonus20() {
        
    }
}